# Generated by Django 5.0.1 on 2024-02-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.category')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.recipes')),
            ],
        ),
    ]
